### ISSUE TITLE
Assignment 1 with Revisions - Ready for Review

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#2]
Hi Carol,

It was great to speak with you earlier today. I am submitting the first assignment with the revisions we discussed. The Rmd and html files are labeled "Assignment 1 - Re-uploading_AL Revisions 9:9:20." 

I will upload the .csv file to Canvas as well. 

Thank you,
Aron

**Comment by saratepfer** [comment]
Great job on this. You did an excellent job integrating Carol's feedback (the feedback I saw here; I'm not sure what you discussed :))
