### ISSUE TITLE
Assignment 2 - Submission

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#3]
Hi Carol,

I am submitting my second assignment. I decided to do the calculations in R and present the data on a pdf. Please find each linked below. They are (not creatively) labeled "Assignment Quant 2."

HTML - https://github.com/SES-5215-F2020/alesser-quant/blob/master/Assignment-Quant-2-.html

PDF - https://github.com/SES-5215-F2020/alesser-quant/blob/master/Quant%20Assignment%202%20Submission_Aron%20Lesser.pdf

I look forward to discussing. 

Best,
Aron

**Comment by saratepfer** [comment]
Thank you, Aron. We are having some trouble viewing the html version of your assignment. According to Carole, when a page build fails, Github usually sends you an email about it. Have you received anything from them? 

Anyway, nice job on the assignment! Your code looks good. Please see a few comments below:

- In your proportion tables, you show the units as percentages, but it looks like you haven't multiplied the raw R outputs by 100. I would do this for consistency.
- You may want to use fewer decimal places in your proportion tables. I would say it's probably appropriate to keep 2-3.

**Comment by a-lesser** [comment]
Hi Sara,

I did receive an email, but when I checked the upload seemed to be in my repository. What exactly does a page build failure mean and how should I approach fixing it?

Thank you for the comments as well. They are very helpful.

-Aron

Aron Lesser
(He/Him/His)
Master's in Urban Planning Candidate, 2022
Harvard University

________________________________
