### ISSUE TITLE
Submission - Assignment 3 Quant - page build failure error

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#4]
Hi Carole,

I am submitting my third assignment. Here is the html link:

https://github.com/SES-5215-F2020/alesser-quant/blob/master/Assingment-Quant-3%202.html

And the RMD: 
https://github.com/SES-5215-F2020/alesser-quant/blob/master/Assingment%20Quant%203%202.Rmd

When I originally uploaded it, I received the same page build failure. I created a new project and re-uploaded (titled Assignment Quant 3 - 2) and received the same error. I will sign up for office hours. 

Thanks,
Aron

**Comment by saratepfer** [comment]
Hi Aron, Were you able to get this sorted out? If so, are you able to reupload your html file for assignment 3? I am having trouble viewing it for grading. 

Thank you,
sara

**Comment by a-lesser** [comment]
Hi Sara,

We figured out the problem. It was a colon in one of the titles.

I will create a new issue and tag you for review.

Thanks,
Aron

Aron Lesser
(He/Him/His)
Master's in Urban Planning Candidate, 2022
Harvard University

________________________________

**Comment by saratepfer** [comment]
Hurray it works! Thank you! I will close this issue and respond with comments in the other one. Thanks again.
