### ISSUE TITLE
New Upload - Assignment Three

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#5]
Hi Sara,

Here is the link to the re-uploaded assignment html and rmd. 

https://SES-5215-F2020.github.io/alesser-quant/Assingment-Quant-3.html
https://SES-5215-F2020.github.io/alesser-quant/Assingment-Quant-3.Rmd

Thanks,
Aron

**Comment by saratepfer** [comment]
Great job, Aron! Please see a few comments below:

- In your interpretations of the Pearson's correlations, I would be sure to comment on the significance in addition to the strength. Your interpretations of the strength are great, but they are missing notes on significance, which is also important.
- For your household size v. ethnicity analysis, based on your code, I don't see how the difference in means is 11. If you have the time, please stop by office hours so we can get it sorted out.
- It would be great to see some interpretation of the Tukey HSD.
- I noticed your note about better understanding the results of the chi-square test. I think Ryan's [assignment 3](https://ses-5215-f2020.github.io/rjohnson-quant/Assignment3Quant.html#Chi-square_test) does a really great job of visualizing the results and providing accompanying interpretation.
