### ISSUE TITLE
Submission - Assignment 4

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#6]
Hi Carole, Sara, and Cat,

Please find below the links to my 4th assignment. 

https://SES-5215-F2020.github.io/alesser-quant/Quant-ASsignment-4.html
https://SES-5215-F2020.github.io/alesser-quant/Quant ASsignment 4.Rmd

Thanks,
Aron

**Comment by saratepfer** [comment]
Nice job, Aron! Please note that you have a typo in line 95. The R squared value is not 1.074; it is 0.1074. This is not an indication of significance as you say; rather, it is an indicator of how much of the variation in the dependent variable is explained by the model.
