### ISSUE TITLE
Assignment 5 Submission

### ISSUE THREAD

**Issue by a-lesser** [SES-5215-F2020/alesser-quant#7]
Hi Carole and team,

Here is my submission for Assignment #5: 

https://SES-5215-F2020.github.io/alesser-quant/Quant Assignment 5.Rmd

https://SES-5215-F2020.github.io/alesser-quant/Quant-Assignment-5.html

Thank you,
Aron

**Comment by saratepfer** [comment]
Nice job on this, Aron. It would be great to see some interpretation of your second graph (line 185), in addition to the interpretation of your first graph. It would also generally be nice to see more detailed interpretation of the meaning of your interactions overall.
